# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

theme: alembic-jekyll-theme

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: jesus_twalter # jekyll-seo-tag > Owners twitter username
author: Jesus Flores # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Jesus Flores # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/jesus_twalter
    - https://www.instagram.com/jesus.floresweb
    - https://www.instagram.com/sasha.kitten_
    - https://github.com/jesus1554
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression

permalink: /:title  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Mexico_City # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Todas las entradas: " # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: es-MX # Set the site language
title: "El Sótano" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.jpg" # Site logo, also used in jekyll-seo-tag
description: "Un blog de cosas interesantes. Post nuevo todas las semanas. In cats we trust" # Site description and default description, also used in jekyll-seo-tag
url: "https://jesus1554.github.io/sotano" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jesus1554/sotano"
email: "jesus.flores.esp@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Categorías
  url: /categorias/
- title: Buscar en el Blog
  url: /search/

navigation_footer:
- title: Creado por Jesús.
  url: https://jesus1554.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/jesus_twalter
  Instagram: https://www.instagram.com/jesus.floresweb
  GitHub: https://github.com/jesus1554
  link: https://jesus1554.github.io
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true
